import { describe, expect, it } from "vitest";
import def, { GView, GRID, toggleCell } from "./g32-lights-grid";
import { DT, input, makeCtx } from "./harness";

const make = () => def.createLogic(makeCtx(`t-${def.id}-${Math.random()}`));

function press(logic: ReturnType<typeof make>, cell: number): void {
  logic.step(DT, input({ padPressed: [cell] }));
}

describe("g32 熄灯谜阵", () => {
  it("toggle 翻转十字五格", () => {
    const lights = new Array(9).fill(false);
    toggleCell(lights, 4);
    expect(lights.filter(Boolean)).toHaveLength(5);
    toggleCell(lights, 4);
    expect(lights.filter(Boolean)).toHaveLength(0);
    toggleCell(lights, 0);
    expect(lights.filter(Boolean)).toHaveLength(3); // corner only touches 3
  });

  it("开局有灯且步数为零", () => {
    const logic = make();
    const v = logic.view as GView;
    expect(v.lights.some(Boolean)).toBe(true);
    expect(v.moves).toBe(0);
    expect(v.lights).toHaveLength(GRID * GRID);
  });

  it("按键会翻转并计步", () => {
    const logic = make();
    logic.start();
    const v = logic.view as GView;
    const before = v.lights.filter(Boolean).length;
    press(logic, 0);
    expect(v.moves).toBe(1);
    expect(v.lights.filter(Boolean).length).not.toBe(before);
  });

  it("重复同一格会还原状态", () => {
    const logic = make();
    logic.start();
    const v = logic.view as GView;
    const before = [...v.lights];
    press(logic, 4);
    press(logic, 4);
    expect(v.lights).toEqual(before);
    expect(v.moves).toBe(2);
  });

  it("全部熄灭时判胜", () => {
    const logic = make();
    logic.start();
    const v = logic.view as GView;
    // A board generated by one center press is solved by pressing it again.
    v.lights = new Array(9).fill(false);
    toggleCell(v.lights, 4);
    press(logic, 4);
    expect(logic.snapshot().status).toBe("over");
    expect(logic.snapshot().detail).toContain("步熄灭");
    expect(logic.snapshot().score).toBeGreaterThan(0);
  });

  it("restart 重排谜面", () => {
    const logic = make();
    logic.start();
    press(logic, 4);
    logic.restart();
    const v = logic.view as GView;
    expect(v.moves).toBe(0);
    expect(logic.snapshot().score).toBe(0);
  });
});
